//go:build linux

// Copyright 2024 Andree Toonk. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package afxdp

import (
	"encoding/binary"
	"fmt"
	"net"
	"net/netip"
	"strconv"
	"strings"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/asm"
)

// A Match is one packet-classification rule for WithFilter. A packet is
// redirected to the AF_XDP sockets if it satisfies ANY of the matches (logical
// OR); everything else is passed to the kernel network stack. Build matches
// with MatchUDPPort, MatchTCPPort, MatchICMPv4Echo, MatchIPv4Proto, MatchEtherType,
// or MatchAll, and combine freely:
//
//	afxdp.Open("eth0", afxdp.WithFilter(
//		afxdp.MatchUDPPort(4789, 51820), // two UDP ports
//		afxdp.MatchICMPv4Echo(),           // ...and ICMP echo requests
//	))
//
// Matches operate on Ethernet + IPv4/IPv6. The port and ICMP builders read L4
// fields at fixed offsets and guard that read: an IPv4 packet with options
// (IHL > 5) or a non-initial fragment does not match, by an explicit header
// check rather than by accident — without it, bytes at the fixed offset could
// spell the requested port and false-match. IPv6 packets with extension
// headers do not match either (Next Header is compared directly). The IP
// (CIDR) builders read fixed address offsets and are unaffected by all of
// this. A single 802.1Q VLAN tag is skipped
// transparently, so the same match works whether or not the NIC strips the tag
// before XDP; stacked QinQ tags are not unwound and such frames do not match.
//
// For classification beyond these builders, NewMatch takes a caller-supplied
// eBPF block and is checked and assembled exactly like the built-ins. Failing
// that, redirect everything and classify in your receive loop.
type Match struct {
	// build emits the eBPF for this rule. On a match it jumps to redirectSym;
	// otherwise it falls through to the physically next block (nextSym, used
	// for its early-exit jumps). entrySym labels its first instruction.
	// It returns an error when the block cannot be produced at all (a cBPF
	// program that will not compile, say); Open surfaces it like any other
	// filter error.
	build func(entrySym, nextSym, redirectSym string) (asm.Instructions, error)
	// desc is a short human-readable summary (e.g. "udp/53") reported by
	// Fleet.Info.
	desc string
	// err, if non-nil, is a construction error (e.g. a bad CIDR passed to
	// MatchSrcIP). Open surfaces it instead of attaching a broken program.
	err error
	// catchAll is true for a match that redirects unconditionally (MatchAll).
	// As an exception that means "pass everything", which is a filter that can
	// never redirect.
	catchAll bool
	// mgmt marks an exception generated by WithKeepManagement, so Fleet.Info
	// can summarise those and name user-supplied ones (WithExcept).
	mgmt bool
	// passOnly is true for a match that never redirects (MatchNone). If every
	// match is passOnly the program has no reachable redirect path, so we emit
	// a minimal pass-everything program instead (the verifier rejects the
	// unreachable redirect block otherwise).
	passOnly bool
}

// portsDesc renders a protocol + optional port list, e.g. "udp/53",
// "tcp/80,443", or just "udp" when no ports are given.
func portsDesc(proto string, ports []uint16) string {
	if len(ports) == 0 {
		return proto
	}
	parts := make([]string, len(ports))
	for i, p := range ports {
		parts[i] = strconv.Itoa(int(p))
	}
	return proto + "/" + strings.Join(parts, ",")
}

// Packet field offsets for Ethernet + IPv4(no options) + L4.
const (
	offEtherType = 12 // u16
	offIPProto   = 23 // u8  (14 + 9)
	offL4Sport   = 34 // u16 (14 + 20 + 0): same for UDP and TCP
	offL4Dport   = 36 // u16 (14 + 20 + 2): same for UDP and TCP
	offICMPType  = 34 // u8  (14 + 20 + 0)

	// IPv6 equivalents. The IPv6 header is a fixed 40 bytes, so L4 starts at
	// 14+40; these are only correct when Next Header is the L4 protocol itself
	// (no extension headers), which is the case for the management traffic
	// these are used for.
	offIPv6NextHdr = 20 // u8  (14 + 6)
	offIPv6L4Sport = 54 // u16 (14 + 40 + 0)
	offIPv6L4Dport = 56 // u16 (14 + 40 + 2)
	offICMPv6Type  = 54 // u8  (14 + 40 + 0)

	// IPv4 header fields at fixed offsets, used to guard the fixed-offset L4
	// reads above: the version+IHL byte and the flags+fragment-offset word.
	offIPv4VerIHL   = 14 // u8: must be 0x45 for the L4 offsets to be right
	offIPv4FragOff  = 20 // u16: low 13 bits are the fragment offset
	ipv4VerIHL5     = 0x45
	ipv4FragOffMask = 0x1fff

	// IP address offsets. These are fixed regardless of IPv4 options or IPv6
	// extension headers, so address matching needs no header walking.
	offIPv4Src = 26 // 14 + 12, 4 bytes
	offIPv4Dst = 30 // 14 + 16, 4 bytes
	offIPv6Src = 22 // 14 + 8, 16 bytes
	offIPv6Dst = 38 // 14 + 24, 16 bytes

	etherTypeARP      = 0x0806
	ipProtoICMP       = 1
	ipProtoTCP        = 6
	ipProtoUDP        = 17
	ipProtoICMPv6     = 58
	icmpEchoRequest   = 8
	icmpv6EchoRequest = 128

	// IPv6 neighbour discovery message types (RFC 4861): router solicitation
	// and advertisement, neighbour solicitation and advertisement, redirect.
	icmpv6NDFirst = 133
	icmpv6NDLast  = 137

	xdpPass = 2
)

// EtherType values as a packet load sees them. Derived through netshort rather
// than hardcoded, so they stay correct on a big-endian host.
var (
	etherTypeIPv4LE = netshort(EtherTypeIPv4)
	etherTypeIPv6LE = netshort(EtherTypeIPv6)
	etherTypeVLANLE = netshort(EtherTypeVLAN) // the 802.1Q TPID; l3Base skips it
)

// netshort returns a 16-bit field's network-byte-order (big-endian) value as a
// packet load sees it, so it can be compared against a loaded u16. eBPF loads
// use the host's byte order, so this is a swap on a little-endian host and the
// identity on a big-endian one.
func netshort(v uint16) int32 {
	var b [2]byte
	binary.BigEndian.PutUint16(b[:], v)
	return int32(binary.NativeEndian.Uint16(b[:]))
}

func withEntry(entry string, ins asm.Instructions) asm.Instructions {
	if len(ins) > 0 {
		ins[0] = ins[0].WithSymbol(entry)
	}
	return ins
}

// boundsFrom emits "if base + n > data_end goto next", bounds-checking a read of
// the first n bytes starting at base. base is R7 (frame start) for the ethertype
// probe, or R9 (the VLAN-adjusted L3 base set by l3Base) for the L3/L4 fields.
func boundsFrom(base asm.Register, n int32, next string) asm.Instructions {
	return asm.Instructions{
		asm.Mov.Reg(asm.R2, base),
		asm.Add.Imm(asm.R2, n),
		asm.JGT.Reg(asm.R2, asm.R6, next),
	}
}

// ipv4FixedL4Guard emits the checks that make a fixed-offset IPv4 L4 read
// honest: IHL must be 5 (with options, offsets 34/36 point into the options,
// and whatever bytes sit there can spell any port — a false match, not a
// missed one) and the fragment offset must be zero (a non-initial fragment
// has payload where the L4 header would be, with the same false-match hazard;
// a first fragment carries the real header and is fine). The caller has
// already confirmed EtherType IPv4 and bounds-checked past offset 22.
func ipv4FixedL4Guard(next string) asm.Instructions {
	return asm.Instructions{
		asm.LoadMem(asm.R3, asm.R9, offIPv4VerIHL, asm.Byte),
		asm.JNE.Imm(asm.R3, ipv4VerIHL5, next),
		asm.LoadMem(asm.R3, asm.R9, offIPv4FragOff, asm.Half),
		asm.And.Imm(asm.R3, netshort(ipv4FragOffMask)),
		asm.JNE.Imm(asm.R3, 0, next),
	}
}

// l3Base sets R9 to the start of the Ethernet frame, transparently stepping over
// a single 802.1Q VLAN tag if one is present. Downstream matchers load their
// fixed field offsets (ethertype +12, IP proto +23, ports +36, addresses
// +26/+30, ...) relative to R9, so they resolve correctly whether the frame
// reaches XDP tagged or already stripped by the NIC. It bounds-checks the
// ethertype read and jumps to next on a runt frame. label must be unique per
// block (callers pass their entry symbol). Only the outermost single C-VLAN is
// unwound; QinQ / stacked tags are not. R9 is scratch here — the redirect tail
// uses R8 (rx_queue_index), not R9.
func l3Base(label, next string) asm.Instructions {
	notag := label + "_notag"
	ins := asm.Instructions{asm.Mov.Reg(asm.R9, asm.R7)} // R9 = data
	ins = append(ins, boundsFrom(asm.R9, offEtherType+2, next)...)
	return append(ins,
		asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
		asm.JNE.Imm(asm.R3, etherTypeVLANLE, notag),
		asm.Add.Imm(asm.R9, 4),                        // step over the 4-byte tag
		asm.Mov.Reg(asm.R9, asm.R9).WithSymbol(notag), // no-op landing pad for the label
	)
}

// matchL4Port builds a port match for one L4 protocol, in one or both address
// families, on either the source or destination port.
//
// Both families are handled in a single block: after the EtherType is known,
// the two branches use their own offsets (IPv4 protocol at 23 and ports at
// 34/36; IPv6 Next Header at 20 and ports at 54/56) and their own bounds
// check, so a short IPv4 packet is not rejected by IPv6's longer reach.
//
// IPv4 options and IPv6 extension headers are not walked: a packet carrying
// either has its L4 header elsewhere and does not match. Use the bpfmatch
// module for those — a pcap-compiled filter handles variable-length IPv4
// headers.
func matchL4Port(proto uint8, srcPort bool, ports []uint16) Match {
	name := "tcp"
	if proto == ipProtoUDP {
		name = "udp"
	}
	if srcPort {
		name += "-src"
	}
	desc := portsDesc(name, ports)
	v4Off, v6Off := int16(offL4Dport), int16(offIPv6L4Dport)
	if srcPort {
		v4Off, v6Off = offL4Sport, offIPv6L4Sport
	}
	return Match{desc: desc, build: func(entry, next, redirect string) (asm.Instructions, error) {
		v4, v6 := entry+"_v4", entry+"_v6"
		// family emits one branch: bounds-check, header-sanity guard for IPv4,
		// protocol test, port tests.
		family := func(label string, protoOff, portOff int16, v4 bool) asm.Instructions {
			b := boundsFrom(asm.R9, int32(portOff)+2, next)
			b[0] = b[0].WithSymbol(label)
			if v4 {
				b = append(b, ipv4FixedL4Guard(next)...)
			}
			b = append(b,
				asm.LoadMem(asm.R3, asm.R9, protoOff, asm.Byte),
				asm.JNE.Imm(asm.R3, int32(proto), next),
			)
			if len(ports) == 0 {
				return append(b, asm.Ja.Label(redirect))
			}
			b = append(b, asm.LoadMem(asm.R3, asm.R9, portOff, asm.Half))
			for _, p := range ports {
				b = append(b, asm.JEq.Imm(asm.R3, netshort(p), redirect))
			}
			return append(b, asm.Ja.Label(next))
		}
		ins := l3Base(entry, next)
		// l3Base proves 14 bytes from the *unadjusted* frame start; after it
		// steps over a VLAN tag the base moved forward, so the EtherType read
		// below needs its own check.
		ins = append(ins, boundsFrom(asm.R9, offEtherType+2, next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
			asm.JEq.Imm(asm.R3, etherTypeIPv4LE, v4),
			asm.JEq.Imm(asm.R3, etherTypeIPv6LE, v6),
			asm.Ja.Label(next),
		)
		ins = append(ins, family(v4, offIPProto, v4Off, true)...)
		ins = append(ins, family(v6, offIPv6NextHdr, v6Off, false)...)
		return withEntry(entry, ins), nil
	}}
}

// MatchUDPPort matches UDP packets whose destination port is one of ports, over
// both IPv4 and IPv6. With no ports it matches all UDP traffic.
//
// Prior to the dual-family change this matched IPv4 only, silently. See
// MatchUDPSrcPort for the source-port equivalent.
func MatchUDPPort(ports ...uint16) Match { return matchL4Port(ipProtoUDP, false, ports) }

// MatchUDPSrcPort matches UDP packets whose *source* port is one of ports, over
// both IPv4 and IPv6 — the direction for replies rather than requests (DNS
// answers, NTP responses). With no ports it matches all UDP traffic.
func MatchUDPSrcPort(ports ...uint16) Match { return matchL4Port(ipProtoUDP, true, ports) }

// MatchTCPPort matches TCP packets whose destination port is one of ports, over
// both IPv4 and IPv6. With no ports it matches all TCP traffic.
//
// Prior to the dual-family change this matched IPv4 only, silently.
func MatchTCPPort(ports ...uint16) Match { return matchL4Port(ipProtoTCP, false, ports) }

// MatchTCPSrcPort matches TCP packets whose *source* port is one of ports, over
// both IPv4 and IPv6. With no ports it matches all TCP traffic.
func MatchTCPSrcPort(ports ...uint16) Match { return matchL4Port(ipProtoTCP, true, ports) }

// MatchICMPv4Echo matches IPv4 ICMP echo-request (ping) packets. For IPv6 see
// MatchICMPv6Echo — the two are different protocols with different numbers, so
// there is no single "ICMP" match.
func MatchICMPv4Echo() Match {
	return Match{desc: "icmpv4-echo", build: func(entry, next, redirect string) (asm.Instructions, error) {
		ins := l3Base(entry, next)
		ins = append(ins, boundsFrom(asm.R9, offICMPType+1, next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
			asm.JNE.Imm(asm.R3, etherTypeIPv4LE, next),
		)
		ins = append(ins, ipv4FixedL4Guard(next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offIPProto, asm.Byte),
			asm.JNE.Imm(asm.R3, ipProtoICMP, next),
			asm.LoadMem(asm.R3, asm.R9, offICMPType, asm.Byte),
			asm.JNE.Imm(asm.R3, icmpEchoRequest, next),
			asm.Ja.Label(redirect),
		)
		return withEntry(entry, ins), nil
	}}
}

// MatchIPv4Proto matches IPv4 packets whose Protocol field is proto (e.g. 47
// for GRE, 50 for ESP).
//
// It is IPv4-only by name because the IPv6 equivalent is not equivalent: IPv6's
// Next Header names whatever comes next, which may be an extension header
// rather than the upper-layer protocol. MatchIPv6NextHeader matches that field
// honestly; neither walks the extension-header chain. Note ordinary tcpdump
// expressions ("ip6 proto 6") do not walk it either — the pcap expression that
// does is "protochain 6", usable through the bpfmatch/pcapfilter layer.
func MatchIPv4Proto(proto uint8) Match {
	return Match{desc: fmt.Sprintf("ipv4-proto/%d", proto), build: func(entry, next, redirect string) (asm.Instructions, error) {
		ins := l3Base(entry, next)
		ins = append(ins, boundsFrom(asm.R9, offIPProto+1, next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
			asm.JNE.Imm(asm.R3, etherTypeIPv4LE, next),
			asm.LoadMem(asm.R3, asm.R9, offIPProto, asm.Byte),
			asm.JNE.Imm(asm.R3, int32(proto), next),
			asm.Ja.Label(redirect),
		)
		return withEntry(entry, ins), nil
	}}
}

// MatchIPv6NextHeader matches IPv6 packets whose Next Header field is nh.
//
// Next Header names what immediately follows the fixed 40-byte IPv6 header,
// which is the upper-layer protocol only when no extension headers are present.
// A packet carrying a Hop-by-Hop or Routing header has nh naming *that*, so
// MatchIPv6NextHeader(6) does not match TCP behind an extension chain. That is
// the honest reading of the field. Ordinary tcpdump expressions read it the
// same way; the pcap expression that does walk the chain is "protochain",
// via the bpfmatch/pcapfilter layer.
func MatchIPv6NextHeader(nh uint8) Match {
	return Match{desc: fmt.Sprintf("ipv6-nexthdr/%d", nh), build: func(entry, next, redirect string) (asm.Instructions, error) {
		ins := l3Base(entry, next)
		ins = append(ins, boundsFrom(asm.R9, offIPv6NextHdr+1, next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
			asm.JNE.Imm(asm.R3, etherTypeIPv6LE, next),
			asm.LoadMem(asm.R3, asm.R9, offIPv6NextHdr, asm.Byte),
			asm.JNE.Imm(asm.R3, int32(nh), next),
			asm.Ja.Label(redirect),
		)
		return withEntry(entry, ins), nil
	}}
}

// MatchICMPv6Echo matches ICMPv6 echo-request (ping6) packets, i.e. Next Header
// 58 and type 128. Like MatchIPv6NextHeader it does not walk extension headers.
func MatchICMPv6Echo() Match {
	return Match{desc: "icmpv6-echo", build: func(entry, next, redirect string) (asm.Instructions, error) {
		ins := l3Base(entry, next)
		ins = append(ins, boundsFrom(asm.R9, offICMPv6Type+1, next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
			asm.JNE.Imm(asm.R3, etherTypeIPv6LE, next),
			asm.LoadMem(asm.R3, asm.R9, offIPv6NextHdr, asm.Byte),
			asm.JNE.Imm(asm.R3, ipProtoICMPv6, next),
			asm.LoadMem(asm.R3, asm.R9, offICMPv6Type, asm.Byte),
			asm.JNE.Imm(asm.R3, icmpv6EchoRequest, next),
			asm.Ja.Label(redirect),
		)
		return withEntry(entry, ins), nil
	}}
}

// MatchEtherType matches packets with the given EtherType (e.g. 0x0806 for ARP,
// 0x86DD for IPv6). Pass the value in host order; MatchEtherType handles the
// byte order. A single 802.1Q tag is skipped first, so this matches the inner
// (encapsulated) EtherType — MatchEtherType(0x0806) catches ARP whether or not
// the frame is tagged.
func MatchEtherType(etherType uint16) Match {
	return Match{desc: fmt.Sprintf("ethertype/0x%04x", etherType), build: func(entry, next, redirect string) (asm.Instructions, error) {
		ins := l3Base(entry, next)
		ins = append(ins, boundsFrom(asm.R9, offEtherType+2, next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
			asm.JNE.Imm(asm.R3, netshort(etherType), next),
			asm.Ja.Label(redirect),
		)
		return withEntry(entry, ins), nil
	}}
}

// MatchSrcIP matches packets whose source IP is inside the given CIDR. The CIDR
// chooses the address family: "10.0.0.0/8" matches IPv4, "2001:db8::/32" matches
// IPv6, a single host is "/32" (v4) or "/128" (v6).
func MatchSrcIP(cidr string) Match { return matchIP(cidr, true) }

// MatchDstIP matches packets whose destination IP is inside the given CIDR. See
// MatchSrcIP for the CIDR format.
func MatchDstIP(cidr string) Match { return matchIP(cidr, false) }

// MatchFlow matches packets whose source IP is in srcCIDR AND whose destination
// IP is in dstCIDR, i.e. one direction of a flow. Both CIDRs must be the same
// address family (IPv4 with IPv4, or IPv6 with IPv6); a single host on a side is
// "/32" or "/128". To match a flow in either direction, OR two of them:
//
//	afxdp.WithFilter(
//		afxdp.MatchFlow("10.0.0.1/32", "10.0.0.2/32"),
//		afxdp.MatchFlow("10.0.0.2/32", "10.0.0.1/32"),
//	)
func MatchFlow(srcCIDR, dstCIDR string) Match {
	src, err := netip.ParsePrefix(srcCIDR)
	if err != nil {
		return Match{desc: "flow(invalid)", err: fmt.Errorf("bad src CIDR %q: %w", srcCIDR, err)}
	}
	dst, err := netip.ParsePrefix(dstCIDR)
	if err != nil {
		return Match{desc: "flow(invalid)", err: fmt.Errorf("bad dst CIDR %q: %w", dstCIDR, err)}
	}
	src, dst = src.Masked(), dst.Masked()
	if src.Addr().Is4() != dst.Addr().Is4() {
		return Match{desc: "flow(invalid)", err: fmt.Errorf("flow src %s and dst %s must be the same address family", src, dst)}
	}
	return Match{
		desc: "src " + src.String() + " & dst " + dst.String(),
		build: func(entry, next, redirect string) (asm.Instructions, error) {
			srcOff, dstOff, et, end := ipOffsets(src.Addr().Is4())
			ins := l3Base(entry, next)
			ins = append(ins, boundsFrom(asm.R9, int32(end), next)...)
			ins = append(ins,
				asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
				asm.JNE.Imm(asm.R3, et, next),
			)
			ins = append(ins, cidrTest(srcOff, src, next)...) // src not in CIDR -> next
			ins = append(ins, cidrTest(dstOff, dst, next)...) // dst not in CIDR -> next
			ins = append(ins, asm.Ja.Label(redirect))         // both matched
			return withEntry(entry, ins), nil
		},
	}
}

func matchIP(cidr string, isSrc bool) Match {
	dir := "dst"
	if isSrc {
		dir = "src"
	}
	prefix, err := netip.ParsePrefix(cidr)
	if err != nil {
		return Match{desc: dir + " ip(invalid)", err: fmt.Errorf("bad CIDR %q: %w", cidr, err)}
	}
	prefix = prefix.Masked()
	return Match{
		desc: dir + " " + prefix.String(),
		build: func(entry, next, redirect string) (asm.Instructions, error) {
			srcOff, dstOff, et, end := ipOffsets(prefix.Addr().Is4())
			off := dstOff
			if isSrc {
				off = srcOff
			}
			ins := l3Base(entry, next)
			ins = append(ins, boundsFrom(asm.R9, int32(end), next)...)
			ins = append(ins,
				asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
				asm.JNE.Imm(asm.R3, et, next),
			)
			ins = append(ins, cidrTest(off, prefix, next)...) // not in CIDR -> next
			ins = append(ins, asm.Ja.Label(redirect))         // matched
			return withEntry(entry, ins), nil
		},
	}
}

// ipOffsets returns the source and destination address offsets, the EtherType to
// require, and the offset just past the destination address (for the bounds
// check that covers both addresses).
func ipOffsets(isV4 bool) (srcOff, dstOff int, et int32, end int) {
	if isV4 {
		return offIPv4Src, offIPv4Dst, etherTypeIPv4LE, offIPv4Dst + 4
	}
	return offIPv6Src, offIPv6Dst, etherTypeIPv6LE, offIPv6Dst + 16
}

// cidrTest emits "if the address at off is NOT inside prefix, jump to fail". On a
// match it falls through. The caller has already bounds-checked and confirmed the
// EtherType. The 32-bit packet loads are little-endian, so the mask and network
// words are computed the same way. IPv6 is checked word by word; words the prefix
// does not cover (zero mask) are skipped.
func cidrTest(off int, prefix netip.Prefix, fail string) asm.Instructions {
	var addr, mask []byte
	if prefix.Addr().Is4() {
		a := prefix.Addr().As4()
		addr, mask = a[:], net.CIDRMask(prefix.Bits(), 32)
	} else {
		a := prefix.Addr().As16()
		addr, mask = a[:], net.CIDRMask(prefix.Bits(), 128)
	}
	var ins asm.Instructions
	for w := 0; w*4 < len(mask); w++ {
		mw := binary.LittleEndian.Uint32(mask[w*4:])
		if mw == 0 {
			continue
		}
		nw := binary.LittleEndian.Uint32(addr[w*4:]) & mw
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, int16(off+w*4), asm.Word),
			asm.And.Imm(asm.R3, int32(mw)),
			asm.JNE.Imm32(asm.R3, int32(nw), fail),
		)
	}
	return ins
}

// matchLocalPort matches packets of the given IP protocol whose source or
// destination L4 port equals port AND whose destination address is local (inside
// local). It is the AND that the public builders cannot express: WithFilter
// combines matches with OR, and keeping management traffic alive needs
// "port 22 AND addressed to this box", so transit traffic on port 22 through a
// router is still captured.
//
// The address family of local selects the IPv4 or IPv6 field offsets. A zero
// Prefix means "any destination", used as the fail-safe when an interface's
// addresses cannot be determined.
func matchLocalPort(proto uint8, srcPort bool, port uint16, local netip.Prefix, family4 bool) Match {
	dir := "dport"
	if srcPort {
		dir = "sport"
	}
	protoName := map[uint8]string{ipProtoTCP: "tcp", ipProtoUDP: "udp"}[proto]
	scope := "any"
	if local.IsValid() {
		scope = local.Addr().String()
		family4 = local.Addr().Is4()
	}
	return Match{
		desc: fmt.Sprintf("%s %s %d -> %s", protoName, dir, port, scope),
		build: func(entry, next, redirect string) (asm.Instructions, error) {
			etherType, protoOff, portOff, dstOff, end := int32(etherTypeIPv4LE),
				int16(offIPProto), int16(offL4Dport), offIPv4Dst, int32(offIPv4Dst+4)
			if srcPort {
				portOff = offL4Sport
			}
			if !family4 {
				etherType, protoOff, portOff, dstOff, end = etherTypeIPv6LE,
					offIPv6NextHdr, offIPv6L4Dport, offIPv6Dst, offIPv6Dst+16
				if srcPort {
					portOff = offIPv6L4Sport
				}
			}
			// Cover both the address and the L4 port with one bounds check.
			if p := int32(portOff) + 2; p > end {
				end = p
			}
			ins := l3Base(entry, next)
			ins = append(ins, boundsFrom(asm.R9, end, next)...)
			ins = append(ins,
				asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
				asm.JNE.Imm(asm.R3, etherType, next),
			)
			// family4 is already resolved against local's family at
			// construction, so it alone decides whether this is the v4 block.
			if family4 {
				ins = append(ins, ipv4FixedL4Guard(next)...)
			}
			ins = append(ins,
				asm.LoadMem(asm.R3, asm.R9, protoOff, asm.Byte),
				asm.JNE.Imm(asm.R3, int32(proto), next),
				asm.LoadMem(asm.R3, asm.R9, portOff, asm.Half),
				asm.JNE.Imm(asm.R3, netshort(port), next),
			)
			if local.IsValid() {
				ins = append(ins, cidrTest(dstOff, local, next)...) // not ours -> next
			}
			ins = append(ins, asm.Ja.Label(redirect))
			return withEntry(entry, ins), nil
		},
	}
}

// matchICMPv6ND matches IPv6 neighbour discovery (RFC 4861 types 133-137).
// Passing these to the kernel is what keeps IPv6 connectivity alive: they are
// the IPv6 equivalent of ARP, and without them the kernel cannot resolve or
// keep the gateway's link-layer address.
func matchICMPv6ND() Match {
	return Match{desc: "icmpv6-nd", build: func(entry, next, redirect string) (asm.Instructions, error) {
		ins := l3Base(entry, next)
		ins = append(ins, boundsFrom(asm.R9, offICMPv6Type+1, next)...)
		ins = append(ins,
			asm.LoadMem(asm.R3, asm.R9, offEtherType, asm.Half),
			asm.JNE.Imm(asm.R3, etherTypeIPv6LE, next),
			asm.LoadMem(asm.R3, asm.R9, offIPv6NextHdr, asm.Byte),
			asm.JNE.Imm(asm.R3, ipProtoICMPv6, next),
			asm.LoadMem(asm.R3, asm.R9, offICMPv6Type, asm.Byte),
			asm.JLT.Imm(asm.R3, icmpv6NDFirst, next),
			asm.JGT.Imm(asm.R3, icmpv6NDLast, next),
			asm.Ja.Label(redirect),
		)
		return withEntry(entry, ins), nil
	}}
}

// managementExceptions builds the rule set that WithKeepManagement passes to the
// kernel instead of redirecting: ARP and IPv6 ND (without which the kernel loses
// the gateway's link-layer address within about a minute and the box goes
// unreachable no matter what else is passed), inbound SSH, return traffic for
// outbound SSH, and DNS replies. XDP is ingress-only, so only inbound rules are
// needed.
//
// locals scopes the port rules to this interface's own addresses. With unscoped
// set the port rules match any destination instead — the fail-safe for when the
// addresses could not be read at all. With neither (no addresses, read
// successfully) only ARP and ND are emitted: nothing can be addressed to an
// interface with no address, so port rules would exclude traffic from the
// capture while protecting nothing.
func managementExceptions(locals []netip.Prefix, tcpPorts []uint16, unscoped bool) []Match {
	type portRule struct {
		proto   uint8
		srcPort bool // match the source port (return traffic) rather than dest
		port    uint16
	}
	ms := []Match{MatchEtherType(etherTypeARP), matchICMPv6ND()}
	var rules []portRule
	for _, p := range tcpPorts {
		rules = append(rules,
			portRule{ipProtoTCP, false, p}, // inbound session to us
			portRule{ipProtoTCP, true, p},  // return traffic for a session we opened
		)
	}
	rules = append(rules,
		portRule{ipProtoUDP, true, 53}, // DNS replies
		portRule{ipProtoTCP, true, 53}, // DNS over TCP replies
	)
	for _, r := range rules {
		if unscoped {
			ms = append(ms,
				matchLocalPort(r.proto, r.srcPort, r.port, netip.Prefix{}, true),
				matchLocalPort(r.proto, r.srcPort, r.port, netip.Prefix{}, false))
			continue
		}
		for _, l := range locals {
			ms = append(ms, matchLocalPort(r.proto, r.srcPort, r.port, l, l.Addr().Is4()))
		}
	}
	for i := range ms {
		ms[i].mgmt = true
	}
	return ms
}

// MatchAll matches every packet. Use it as a catch-all, or on its own it is
// equivalent to running with no filter at all.
func MatchAll() Match {
	return Match{desc: "all", catchAll: true, build: func(entry, _, redirect string) (asm.Instructions, error) {
		return withEntry(entry, asm.Instructions{asm.Ja.Label(redirect)}), nil
	}}
}

// MatchNone matches nothing: every packet is passed to the kernel, none is
// redirected. On its own (afxdp.WithFilter(afxdp.MatchNone())) it attaches the
// XDP program — which is what enables a driver's zero-copy datapath — without
// stealing any receive traffic. That's exactly what a transmit-only program
// (a packet generator) wants: zero-copy TX without disturbing the host's RX.
func MatchNone() Match {
	return Match{
		desc:     "none",
		passOnly: true,
		build: func(entry, next, _ string) (asm.Instructions, error) {
			return withEntry(entry, asm.Instructions{asm.Ja.Label(next)}), nil
		},
	}
}

// filterDesc renders a set of matches as a short human-readable summary, e.g.
// "udp/53" or "udp/4789 | icmp-echo". No matches means the program redirects
// everything, reported as "all". Exceptions are summarised rather than listed:
// the management preset expands to a dozen or more blocks and printing them all
// would bury the part the operator cares about.
func filterDesc(matches []Match, exceptions []Match) string {
	desc := "all"
	if len(matches) > 0 {
		descs := make([]string, len(matches))
		for i, m := range matches {
			descs[i] = m.desc
		}
		desc = strings.Join(descs, " | ")
	}
	if n := len(exceptions); n > 0 {
		descs := make([]string, 0, n)
		mgmt := 0
		for _, e := range exceptions {
			if e.mgmt {
				mgmt++
				continue
			}
			descs = append(descs, e.desc)
		}
		switch {
		case mgmt > 0 && len(descs) > 0:
			desc += fmt.Sprintf(" (except %d mgmt rules: arp, nd, ssh, dns; and %s)",
				mgmt, strings.Join(descs, ", "))
		case mgmt > 0:
			desc += fmt.Sprintf(" (except %d mgmt rules: arp, nd, ssh, dns)", mgmt)
		default:
			desc += " (except " + strings.Join(descs, ", ") + ")"
		}
	}
	return desc
}

// classifierBlocks emits the classification blocks for a filter program: the
// exception blocks first, each redirecting to "pass" (a hit leaves the packet
// with the kernel and never reaches the accept blocks), then the match blocks,
// each redirecting to "redirect". The caller provides the prologue (R6/R7/R8)
// and the "pass" and "redirect" tails. Shared between newFilterProgram and the
// dry-run test harness so the two cannot drift.
//
// Every emitted block is checked against the register contract (see checkBlock)
// before it is accepted, so a block that would silently misbehave at line rate
// becomes an error from Open instead.
func classifierBlocks(exceptions, matches []Match) (asm.Instructions, error) {
	if err := validateMatches(exceptions, matches); err != nil {
		return nil, err
	}
	var insns asm.Instructions
	emit := func(m Match, entry, next, redirect string) error {
		ins, err := m.build(entry, next, redirect)
		if err != nil {
			return fmt.Errorf("afxdp: filter: match %q: %w", m.desc, err)
		}
		if err := checkBlock(ins); err != nil {
			return fmt.Errorf("afxdp: filter: match %q: %w", m.desc, err)
		}
		insns = append(insns, ins...)
		return nil
	}
	for i, e := range exceptions {
		next := "match0"
		if i+1 < len(exceptions) {
			next = fmt.Sprintf("except%d", i+1)
		}
		if err := emit(e, fmt.Sprintf("except%d", i), next, "pass"); err != nil {
			return nil, err
		}
	}
	for i, m := range matches {
		next := "pass"
		if i+1 < len(matches) {
			next = fmt.Sprintf("match%d", i+1)
		}
		if err := emit(m, fmt.Sprintf("match%d", i), next, "redirect"); err != nil {
			return nil, err
		}
	}
	return insns, nil
}

// validateMatches rejects Match values that cannot be assembled, so a bad one
// produces an error rather than a nil dereference during assembly. Called by
// classifierBlocks, so every assembly path is covered.
func validateMatches(exceptions, matches []Match) error {
	// An exception that matches everything passes every packet to the kernel,
	// leaving the redirect path unreachable. The verifier would reject that
	// with a bare "unreachable insn"; say what actually happened instead.
	for _, e := range exceptions {
		if e.catchAll {
			return fmt.Errorf("afxdp: filter: exception %q matches every packet, "+
				"so nothing can be redirected", e.desc)
		}
	}
	for _, m := range append(append([]Match{}, exceptions...), matches...) {
		if m.err != nil {
			return fmt.Errorf("afxdp: filter: match %q: %w", m.desc, m.err)
		}
		// A zero Match (var m afxdp.Match, or a struct literal) has no build
		// func. Catch it here rather than nil-panicking during assembly.
		if m.build == nil {
			return fmt.Errorf("afxdp: filter: match %q has no build func "+
				"(use a Match* builder or NewMatch, not a zero Match)", m.desc)
		}
	}
	return nil
}

// newFilterProgram assembles an XDP program from the given matches. A packet is
// redirected if any match matches; otherwise it is passed to the kernel. The
// redirect path reuses the same qidconf gate + redirect_map tail as NewProgram,
// so binding a subset of queues stays safe (unbound queues pass, not drop).
//
// exceptions are evaluated first and win: a packet matching any of them is
// passed to the kernel without ever being offered to the matches. They are
// ordinary Matches assembled with "pass" as their redirect target, which is what
// makes any builder usable as an exclusion (see WithKeepManagement).
func newFilterProgram(maxQueues int, exceptions, matches []Match, frags bool) (*Program, error) {
	if len(matches) == 0 {
		return nil, fmt.Errorf("afxdp: newFilterProgram needs at least one match")
	}
	// If no match can redirect (e.g. only MatchNone), emit a minimal program
	// that passes everything. It still attaches — enabling zero-copy on the
	// driver for a transmit-only program — but redirects nothing and needs no
	// maps. (A redirect block with nothing jumping to it is unreachable code,
	// which the verifier rejects.)
	anyRedirect := false
	for _, m := range matches {
		if !m.passOnly {
			anyRedirect = true
			break
		}
	}
	if !anyRedirect {
		prog, err := ebpf.NewProgram(&ebpf.ProgramSpec{
			Name:         "xsk_pass",
			Type:         ebpf.XDP,
			Flags:        fragsFlag(frags),
			Instructions: asm.Instructions{asm.Mov.Imm(asm.R0, xdpPass), asm.Return()},
			License:      "LGPL-2.1 or BSD-2-Clause",
		})
		if err != nil {
			return nil, fmt.Errorf("afxdp: load pass-only XDP program: %w", err)
		}
		return &Program{Program: prog}, nil // no maps: nothing is redirected
	}
	// Assemble the classification blocks before allocating any map. This runs
	// caller-supplied build funcs (NewMatch), which can fail or panic; doing it
	// first means no map file descriptor can be leaked by unwinding past the
	// Close calls below. The blocks do not reference the maps — only the
	// redirect tail does.
	blocks, err := classifierBlocks(exceptions, matches)
	if err != nil {
		return nil, err
	}

	qidconf, err := ebpf.NewMap(&ebpf.MapSpec{
		Name:       "qidconf_map",
		Type:       ebpf.Array,
		KeySize:    uint32(unsafe.Sizeof(int32(0))),
		ValueSize:  uint32(unsafe.Sizeof(int32(0))),
		MaxEntries: uint32(maxQueues),
	})
	if err != nil {
		return nil, fmt.Errorf("afxdp: create qidconf_map (try raising RLIMIT_MEMLOCK): %w", err)
	}
	xsks, err := ebpf.NewMap(&ebpf.MapSpec{
		Name:       "xsks_map",
		Type:       ebpf.XSKMap,
		KeySize:    uint32(unsafe.Sizeof(int32(0))),
		ValueSize:  uint32(unsafe.Sizeof(int32(0))),
		MaxEntries: uint32(maxQueues),
	})
	if err != nil {
		qidconf.Close()
		return nil, fmt.Errorf("afxdp: create xsks_map (try raising RLIMIT_MEMLOCK): %w", err)
	}

	// r6 = data_end, r7 = data, r8 = rx_queue_index (callee-saved across the
	// map_lookup_elem call in the redirect tail).
	insns := asm.Instructions{
		asm.LoadMem(asm.R6, asm.R1, 4, asm.Word),
		asm.LoadMem(asm.R7, asm.R1, 0, asm.Word),
		asm.LoadMem(asm.R8, asm.R1, 16, asm.Word),
	}
	insns = append(insns, blocks...)
	insns = append(insns,
		asm.Mov.Imm(asm.R0, xdpPass).WithSymbol("pass"),
		asm.Return(),

		asm.StoreMem(asm.RFP, -4, asm.R8, asm.Word).WithSymbol("redirect"),
		asm.Mov.Reg(asm.R2, asm.RFP),
		asm.Add.Imm(asm.R2, -4),
		asm.LoadMapPtr(asm.R1, qidconf.FD()),
		asm.FnMapLookupElem.Call(),
		asm.JEq.Imm(asm.R0, 0, "pass"),
		asm.LoadMem(asm.R1, asm.R0, 0, asm.Word),
		asm.JEq.Imm(asm.R1, 0, "pass"),
		asm.LoadMapPtr(asm.R1, xsks.FD()),
		asm.Mov.Reg(asm.R2, asm.R8),
		asm.Mov.Imm(asm.R3, 0),
		asm.FnRedirectMap.Call(),
		asm.Return(),
	)

	prog, err := ebpf.NewProgram(&ebpf.ProgramSpec{
		Name:         "xsk_filter",
		Type:         ebpf.XDP,
		Flags:        fragsFlag(frags),
		Instructions: insns,
		License:      "LGPL-2.1 or BSD-2-Clause",
	})
	if err != nil {
		qidconf.Close()
		xsks.Close()
		return nil, fmt.Errorf("afxdp: load filter XDP program: %w", err)
	}
	return &Program{Program: prog, Queues: qidconf, Sockets: xsks}, nil
}
